import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import HeaderNavbar from "@/components/headerNavbar";
import { ScrollProvider } from "@/context/ScrollContext";
import Script from "next/script";
import Footer from "@/components/footer";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Hiraya",
  description: "Generated by The Huntrix",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={plusJakartaSans.variable}>
      <head>
        <Script src='https://www.noupe.com/embed/01984fd9285d7c2d834d0f6cf7d0c68cb148.js' />
      </head>
      <body className="antialiased">
        <ScrollProvider>
          <HeaderNavbar />
          {children}
          <Footer />
        </ScrollProvider>
      </body>
    </html>
  );
}