
import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import HeaderNavbar from "@/components/headerNavbar";
import { ScrollProvider } from "@/context/ScrollContext";
import Footer from "@/components/footer";
import Providers from "./provider";
import Script from "next/script";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Hiraya",
  description: "Generated by The Huntrix",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={plusJakartaSans.variable}>
      {/* <head>
        <Script src='https://www.noupe.com/embed/0198ea057d447e0481f2ee18458d1e1baf1e.js' />
      </head> */}
      <body className="antialiased">
        <ScrollProvider>
          <Providers>
            <HeaderNavbar />
            {children}
          </Providers>
          <Footer />
        </ScrollProvider>
      </body>
      <Script
        src="https://app.wonderchat.io/scripts/wonderchat.js"
        data-name="wonderchat"
        data-address="app.wonderchat.io"
        data-id="cmetjykiw1djrhzs77zv31xsd"
        data-widget-size="normal"
        data-widget-button-size="normal"
        defer
      ></Script>
    </html>
  );
}